### ISSUE TITLE
On iOS 13 it works only one time per respring

### ISSUE THREAD

**Issue by Nikostito** [arandomdev/NFCBackgroundEnabler#1]
iOS 13.3 iPhone 7. It can Background Read a tag only once per respring. Afetrwards nfcd will crash and it will not restart until you respring the device. Is there a possibility it can be updated for iOS13 or is the project dead?

**Comment by arandomdev** [comment]
The project is actually built for IOS 13.3. Can you provide crash logs and user settings, so I can better diagnose the issue.

**Comment by Nikostito** [comment]
> The project is actually built for IOS 13.3. Can you provide crash logs and user settings, so I can better diagnose the issue.

Hey sure can. Just a fix in my previous post. I have it alongside NfcActivator. I saw that it is for iOS 12.x only so I removed it but still I face the issue so it was not the culprit.
Here’s the crash log:
https://pastebin.com/yp28idp0

**Comment by arandomdev** [comment]
NFCBackgroundEnabler is supposed to be used independently from NFCBackground, so uninstall that along with NFCShortcuts and NFCActivator. After this, ldrestart and try again.

Maybe an incompatibility with NFCWriter? Try uninstalling it, ldrestart, and try again.

lastly, assuming that you're on the latest version, try turning off "SMART TAG LOCK" in the preferences.

**Comment by Nikostito** [comment]
So after purging nfcwriter the crashes stopped but again, I can only read my tag once. After that it just stops reading it. Also after disabling smart tag I didn’t notice any difference . I am a dev (not with Obj-c) and I can help you debug it if you need help, maybe with frida.

**Comment by arandomdev** [comment]
I assumed that you uninstalled NFCBackground and that it still didn't work.

If you want to help me debug...

1. compile a debug package, or install [this](https://drive.google.com/open?id=1Ut1qCSWCSrfThMo6VdAm3am2xY-Le6Vm)
2. use oslog or any logging app, and filter for NFCBackgroundEnabler.
3. open another console and execute "killall -9 nfcd"
4. place the tag, remove the tag for a couple of seconds, and place again.
5. report back what the logging app returned.

Thanks!
