### ISSUE TITLE
ios 14.6 compatibility  ?

### ISSUE THREAD

**Issue by cyber-junkie9** [arandomdev/NFCBackgroundEnabler#5]
Does this tweak works with ios 14.6 ?
device - iPhone 7 jail-broken with checkra1n

I've installed tweak from your repo ,created new automation as shown in Reddit video but its not doing any task while scanning tag

**Comment by arandomdev** [comment]
I don’t have a device on 14.6 to check, but it might have broken. Unfortunately this project is kinda in a dead state as I don’t have a lot of time.

but you can try the following,
Run killall -9 nfcd
Restart springboard 
Make sure your tag is readable by trying to read it through a reader app on the AppStore.

Sorry I can’t  provide anymore help.
